torch_start_method: 'spawn'
randomseed: 0

acc_threshold: 20
local_maximum_distance: 20

last_epoch: 200

GPGPU:
  device_ids: [0]

SCL: True
trained_scl_model_path: results/1216_039_FlipSCL_BN_hard/model_checkpoint/last_model.tar

finetune: False
model_for_finetune: results/1216_039_FlipSCL_BN_hard_DOA/model_checkpoint_SD/last_model.tar  # only for fine-tuning