torch_start_method: 'spawn'
randomseed: 0

acc_threshold: 20
local_maximum_distance: 20

last_epoch: 200
resume_epoch: 18

GPGPU:
  device_ids: [0]

SCL: True
trained_scl_model_path: ./results/0911_NegConstMargin_minus/model_checkpoint/last_model.tar

finetune: True
# finetune : resume할 때는 True로!
model_for_finetune: ./results/0911_NegConstMargin_minus_DOA/model_checkpoint/last_model.tar  # only for fine-tuning