torch_start_method: 'spawn'
randomseed: 0

acc_threshold: 20
local_maximum_distance: 20

last_epoch: 200

GPGPU:
  device_ids: [0]

SCL: True
trained_scl_model_path: results/1224_039_SCL_GN_hard_CL/model_checkpoint/last_model.tar

finetune: True
model_for_finetune: results/1224_039_SCL_GN_hard_DOA/model_checkpoint_SD/last_model.tar  # only for fine-tuning